language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install coveralls coverage
    - python bootstrap.py
    - bin/buildout
script:
    - coverage run bin/test -v1
after_success:
    - coverage combine
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
